# Generated by Django 2.0.5 on 2018-10-30 06:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0003_auto_20180513_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='library',
            name='ending_time',
            field=models.DateField(default=datetime.datetime(2018, 11, 29, 14, 26, 39, 974586), verbose_name='应还时间'),
        ),
    ]
